### ISSUE TITLE
[Critical issue] Does not work in Python 3.10

### ISSUE THREAD

**Issue by ZhymabekRoman** [magmax/python-inquirer#122]
Hello, thank you so much for the library, while running the example from the Readme, I found that the library does not function in the latest version of Python 3.10:
```python
~/git/translate $ python3
Python 3.10.0 (default, Oct  6 2021, 01:24:16) [Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c8554895 on linux
Type "help", "copyright", "credits" or "license" for more information. >>> import inquirer
An error was found, but returning just with the version: Blessed needs Python 3.2.3 or greater for Python 3 support due to http://bugs.python.org/issue10570.
>>> questions = [
...   inquirer.List('size',
...                 message="What size do you need?",
...                 choices=['Jumbo', 'Large', 'Standard', 'Medium', 'Small', 'Micro'],
...             ),
... ]
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: module 'inquirer' has no attribute 'List'              >>> answers = inquirer.prompt(questions)
```

**Comment by victorteokw** [comment]
Same issue here.

**Comment by marafa** [comment]
if you are using pipenv , this worked for me `pipenv install  blessed==1.19.0 --skip-lock`

at the same time, a new release would be nice. took me a while to find this solution and i am sure others will have the same issue. fedora 35 now uses python 3.10 as the default version

**Comment by alejandro-angulo** [comment]
Hi @magmax sorry to ping you directly but I was hoping you'd have some time to take a look at this issue and its related PR since inquirer is broken when used with the latest version of python.

**Comment by jmz7v** [comment]
Not 100% related but for anyone looking into solving the issue presented here without pipenv:
```
pipenv install  blessed==1.19.0 --skip-lock
```
That works for pipenv but not for pip, in pip, you could do:
```
pip install blessed==1.19.0 --ignore-requires-python
```
